import { Knex } from "knex";
import fs from "fs";
import path from "path";

import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Seeds province → district → ward from the pre-generated GHN seed SQL.
 * Run order is critical to satisfy FK constraints: province → district → ward.
 *
 * The SQL file is generated by sql/ghn_locations_seed.js which:
 *  - Calls GHN /province, /district, /ward APIs
 *  - Filters out province_name > 20 chars and district_name > 20 chars
 *  - Parses WardCode strings to INT (skips duplicates)
 *  - Inserts province_id, district_id, ward_id directly (no IDENTITY — plain INT NOT NULL)
 */
export async function seed(knex: Knex): Promise<void> {
  const provinceCount = await knex("province")
    .count("province_id as c")
    .first();
  if (Number(provinceCount?.c) > 0) {
    console.log("GHN locations already seeded — skipping.");
    return;
  }

  const sqlPath = path.resolve(__dirname, "../sql/ghn_locations_seed.sql");

  if (!fs.existsSync(sqlPath)) {
    console.warn(
      `GHN seed SQL not found at ${sqlPath}. Run sql/ghn_locations_seed.js first to generate it.`,
    );
    return;
  }

  const sql = fs.readFileSync(sqlPath, "utf-8");
  await knex.raw(sql);
  console.log("GHN location data seeded (province, district, ward).");
}
